# Generated by Django 4.1 on 2022-09-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=150)),
                ('Last_name', models.CharField(max_length=150)),
                ('City', models.CharField(max_length=150)),
                ('Pincode', models.IntegerField()),
                ('Phone_No', models.IntegerField()),
            ],
        ),
    ]
